### ISSUE TITLE
Exception when trying to create new ALE project on linux

### ISSUE THREAD

**Issue by dvojtise** [gemoc/ale-lang#158]
The ALE project creation wizard crashes with an exception
apparently it tries to open the ecore file but this file is not available yet (it should be created by the wizard)

Step to reproduce:
from an Eclipse 2020-03 (either GEMOC studio bump_2020-03 branch or Eclipse Modeling package) (on linux)
get latest ale source from master
launch second workspace
File > New > Project > ALE Project > Next > (provide some name to the project) > Next > Finish

produce the following stack trace:
```
java.lang.reflect.InvocationTargetException: An error occurred while creating the new ALE project test
An error occurred while creating the new ALE project test
  java.lang.reflect.InvocationTargetException: An error occurred while creating the new ALE project test
  	at org.eclipse.emf.ecoretools.ale.ide.ui.wizards.NewAleProjectWizard$1.run(NewAleProjectWizard.java:129)
  	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
  Caused by: org.eclipse.core.runtime.CoreException: /test/model/test.ecore (No such file or directory)
  	at org.eclipse.emf.ecoretools.ale.ide.ui.project.WorkspaceAleProject$Template.lambda$0(WorkspaceAleProject.java:131)
  	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
  	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2278)
  	at org.eclipse.emf.ecoretools.ale.ide.ui.project.WorkspaceAleProject$Template.create(WorkspaceAleProject.java:137)
  	at org.eclipse.emf.ecoretools.ale.ide.ui.wizards.NewAleProjectWizard$1.run(NewAleProjectWizard.java:126)
  	... 1 more
  Caused by: java.io.FileNotFoundException: /test/model/test.ecore (No such file or directory)
  	at java.io.FileOutputStream.open0(Native Method)
  	at java.io.FileOutputStream.open(FileOutputStream.java:270)
  	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
  	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
  	at org.eclipse.emf.ecore.resource.impl.FileURIHandlerImpl$1.<init>(FileURIHandlerImpl.java:65)
  	at org.eclipse.emf.ecore.resource.impl.FileURIHandlerImpl.createOutputStream(FileURIHandlerImpl.java:65)
  	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createOutputStream(ExtensibleURIConverterImpl.java:347)
  	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.save(ResourceImpl.java:1041)
  	at org.eclipse.emf.ecoretools.ale.ide.ui.project.WorkspaceAleProject$Template.createEcoreModel(WorkspaceAleProject.java:189)
  	at org.eclipse.emf.ecoretools.ale.ide.ui.project.WorkspaceAleProject$Template.getOrCreateEcoreModel(WorkspaceAleProject.java:171)
  	at org.eclipse.emf.ecoretools.ale.ide.ui.project.WorkspaceAleProject$Template.lambda$0(WorkspaceAleProject.java:121)
  	... 5 more

```

**Comment by dvojtise** [comment]
similar issue when trying to open using an existing ecore  (in the following trace, I tried to reuse the helloworld.ecore from the ale basic example

```
java.lang.reflect.InvocationTargetException: An error occurred while creating the new ALE project zfzafaz
An error occurred while creating the new ALE project zfzafaz
  java.lang.reflect.InvocationTargetException: An error occurred while creating the new ALE project zfzafaz
  	at org.eclipse.emf.ecoretools.ale.ide.ui.wizards.NewAleProjectWizard$1.run(NewAleProjectWizard.java:129)
  	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
  Caused by: org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: java.io.FileNotFoundException: /helloworld/model/helloworld.ecore (No such file or directory)
  	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
  	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
  	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:406)
  	at org.eclipse.emf.ecoretools.ale.ide.ui.project.WorkspaceAleProject$Template.getEcoreModel(WorkspaceAleProject.java:210)
  	at org.eclipse.emf.ecoretools.ale.ide.ui.project.WorkspaceAleProject$Template.getOrCreateEcoreModel(WorkspaceAleProject.java:174)
  	at org.eclipse.emf.ecoretools.ale.ide.ui.project.WorkspaceAleProject$Template.lambda$0(WorkspaceAleProject.java:121)
  	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
  	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2278)
  	at org.eclipse.emf.ecoretools.ale.ide.ui.project.WorkspaceAleProject$Template.create(WorkspaceAleProject.java:137)
  	at org.eclipse.emf.ecoretools.ale.ide.ui.wizards.NewAleProjectWizard$1.run(NewAleProjectWizard.java:126)
  	... 1 more
  Caused by: java.io.FileNotFoundException: /helloworld/model/helloworld.ecore (No such file or directory)
  	at java.io.FileInputStream.open0(Native Method)
  	at java.io.FileInputStream.open(FileInputStream.java:195)
  	at java.io.FileInputStream.<init>(FileInputStream.java:138)
  	at org.eclipse.emf.ecore.resource.impl.FileURIHandlerImpl.createInputStream(FileURIHandlerImpl.java:99)
  	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:358)
  	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1314)
  	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
  	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
  	... 9 more
 
```

I suspect a mismatch between eclipse path ( /<projectName>/<folder>/<resource>)  being passed as a linux system uri ( where `/` stands for the root of the system on linux)

**Comment by echebbi** [comment]
Or maybe `URI.createFileURI(new File(ecoreFile.getFullPath().toOSString()).getAbsolutePath())`? 

We may also want to check wherever `URI::create` methods are used; e.g. in [AleLaunchConfigurationTab](https://github.com/gemoc/ale-lang/blob/265f9467054f2266df76215dd9b195d57c6ca751/plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/launchconfig/AleLaunchConfigurationTab.java#L279) I used something like:
 - `resources.getResource(URI.createPlatformResourceURI(resource.getFullPath().toPortableString(), true), true);`.

To be honest I'm trully puzzled by the countless ways to deal with paths in Eclipse. For the record, culprit code is [here](https://github.com/gemoc/ale-lang/blob/265f9467054f2266df76215dd9b195d57c6ca751/plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/project/WorkspaceAleProject.java#L179-L189) and [here](https://github.com/gemoc/ale-lang/blob/265f9467054f2266df76215dd9b195d57c6ca751/plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/project/WorkspaceAleProject.java#L210).

**Comment by echebbi** [comment]
I'm so puzzled I've started a utility class that abstracts everything away from me: [`IOResources`](https://github.com/gemoc/ale-lang/blob/265f9467054f2266df76215dd9b195d57c6ca751/plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/io/IOResources.java#L34).

Once the "good" way to deal with those resources/URIs is found I advise to create a dedicated method in this class and to use it wherever needed.
